# Generated by Django 6.0.3 on 2026-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lemba_faculdade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="Interacao",
        ),
    ]
