# Generated by Django 6.0.3 on 2026-03-06 19:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lemba_faculdade", "0002_cliente_activo_delete_interacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("endereco", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="activo",
        ),
        migrations.AddField(
            model_name="cliente",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lemba_faculdade.empresa",
            ),
        ),
        migrations.CreateModel(
            name="interacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_interacao", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lemba_faculdade.cliente",
                    ),
                ),
            ],
        ),
    ]
