# Generated by Django 6.0.3 on 2026-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lemba_faculdade",
            "0003_empresa_remove_cliente_activo_cliente_data_criacao_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
