# Generated by Django 6.0.3 on 2026-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("criado_em", models.DateField(auto_now_add=True)),
                ("data_entrega", models.DateField()),
                ("finalizado_em", models.DateField(null=True)),
            ],
        ),
    ]
