# Generated by Django 6.0.3 on 2026-03-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="criado_em",
            field=models.DateField(auto_now_add=True, verbose_name="Data De Entrega"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="titulo",
            field=models.CharField(max_length=100, verbose_name="Título"),
        ),
    ]
