# Generated by Django 6.0.3 on 2026-03-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todo_criado_em_alter_todo_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="criado_em",
            field=models.DateField(auto_now_add=True, verbose_name="Data de Entrega"),
        ),
    ]
